services:
  postgres:
    image: postgres:latest
    container_name: fitfind_db
    environment:
      POSTGRES_DB: fitfind
      POSTGRES_USER: fitfind
      POSTGRES_PASSWORD: secret
    ports:
      - '5432:5432'
