spring.application.name=FitFind
spring.main.allow-bean-definition-overriding=true

spring.datasource.url=jdbc:postgresql://localhost:5432/fitfind
spring.datasource.username=fitfind
spring.datasource.password=secret

spring.jpa.hibernate.ddl-auto=create-drop
spring.flyway.enabled=false
