package com.fitfind.fitfind.ai.model;

public enum Clothes {
    FULL_OUTFIT, SHIRT, T_SHIRT, DRESS, CROP_TOP, TROUSERS, SKIRT, SHORTS, JACKET, TRENCHCOAT, COAT, BLOUSE, HAT, SHOES, BOOTS, HIGH_HEELS, BAG, HANDBAG, PURSE
}
