spring.application.name=FitFind
spring.main.allow-bean-definition-overriding=true

spring.datasource.url=jdbc:postgresql://localhost:5433/fitfind
spring.datasource.username=fitfind
spring.datasource.password=secret

spring.jpa.hibernate.ddl-auto=create-drop
# CORS configuration for local front-end development
# - allowed-origins: Whitelisted origins (e.g., Angular server on :4200)
# - allowed-methods: HTTP methods allowed
app.cors.allowed-origins[0]=http://localhost:4200
app.cors.allowed-methods[0]=GET
app.cors.allowed-methods[1]=POST
app.cors.allowed-methods[2]=PUT
app.cors.allowed-methods[3]=DELETE
app.cors.allowed-methods[4]=OPTIONS
app.cors.allowed-methods[5]=PATCH
app.cors.allowed-headers[0]=*
# rate limit configuration for auth API calls:
# email/password login: 5 attempts per 10 minutes
app.rate-limit.types.CLIENT_LOGIN.cooldown=10m
app.rate-limit.types.CLIENT_LOGIN.capacity=5

# ai config

# add these as .env variables:
# .env var name: AI_GITHUB_MODELS_KEY
ai.github-models.key=${GITHUB_MODELS_TOKEN}

# .env var name: AI_GITHUB_MODELS_MODEL
ai.github-models.model=gpt-5-mini

# .env var name: AI_GITHUB_MODELS
ai.github-models.endpoint=https://models.github.ai/inference
